### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by minouei-kl** [LivingSkyTechnologies/Document_Layout_Segmentation#3]
Hi,
Congrats on your work. would you express how should we cite it?

**Comment by Lambert-Shirzad** [comment]
@logan-markewich Please advise.

**Comment by logan-markewich** [comment]
@minouei-kl  Thank you! Apologies for the delayed reply.

Currently, we have a paper in review with [IJDAR](https://www.springer.com/journal/10032), but it is probably still several months away from being published.

For now, you can cite with the following bibtex:
```
@misc{LST2021,
  author = {Markewich, Logan and Zhang, Hao and Xing, Yubin and Lambert-Shirzad, Navid and Jiang, Zhexin and Lee, RKW and Li, Zhi and Ko, Seok-bum},
  title = {Document Layout Segmentation},
  year = {2021},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/LivingSkyTechnologies/Document_Layout_Segmentation}},
  commit = {8a470eb2de2129b2e42220a39627a9750969f3bf}
}
```
